ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

# Серверное решение
postgres:
  url: "jdbc:postgresql://176.114.71.165:5432/maindatabase"
  user: selectel
  password: "2318"

# Тестовое решение
#postgres:
#  url: "jdbc:postgresql://localhost:5432/HandBook"
#  user: sharky
#  password: ""

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
